url: http://javajing.com
webmaster: UpgradingDave
email: upgradingdave@gmail.com
name: JavaJing Java Screencasts
description: New screencast each week about java technologies useful for getting stuff done

